#!/usr/bin/env node

/**
 * Check that pnpm is available. If not, ask the user to run `corepack enable`
 * which will provide it.
 */

// no external deps can be used here, because this runs before deps are installed
const { execSync } = require('child_process');
const { stdout } = require('process');
const { colourise, log, warn } = require('../log');

// we can't use chalk, because this runs before deps are installed
// https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
const reset = '\x1b[0m';
const blue = '\x1b[34m';

try {
	const pnpmVersion = execSync('pnpm -v', { encoding: 'utf-8' });
	log(`Using pnpm ${colourise(reset, colourise(blue, pnpmVersion.trim()))}`);
} catch (e) {
	warn(`Could not find pnpm. Please run 'corepack enable'.`);
	process.exit(1);
}
