name: AR CI

on:
  push:
  workflow_dispatch:

# Allow queued workflows to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ar: ${{ steps.filter.outputs.ar }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # the ar filter should be true if any file outside dotcom-rendering/ has changed
          filters: |
            ar:
              - './!(dotcom-rendering)/**'

  skip_build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.ar == 'false' }}
    steps:
      - name: exit
        run: |
          echo "Exiting early, there are no changes to Apps Rendering"
          exit 0

  build:
    name: AR CI
    needs: changes
    if: ${{ needs.changes.outputs.ar == 'true' }}
    runs-on: ubuntu-latest
    # Allow GitHub to request an OIDC JWT ID token, to use with aws-actions/configure-aws-credentials
    permissions:
      id-token: write
      contents: read

    # Checkout the repository
    steps:
      - uses: actions/checkout@v4

      # Get the desired version of Node installed
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          yarn --silent --frozen-lockfile

      # Execute some tasks from the `apps-rendering/package.json` file, using `yarn`
      - name: Build and package
        working-directory: apps-rendering
        run: |
          yarn test
          yarn build:client:prod
          yarn build:server:prod
          yarn copy-manifest
          yarn copy-fonts
          yarn synth
          zip -j dist/server/mobile-apps-rendering.zip dist/server/*

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v2.2.2
        with:
          configPath: apps-rendering/riff-raff.yaml
          projectName: Mobile::mobile-apps-rendering
          buildNumberOffset: 27000 # This is the last build number from TeamCity
          contentDirectories: |
            mobile-apps-rendering-cfn:
              - apps-rendering/cdk.out/MobileAppsRendering-CODE.template.json
              - apps-rendering/cdk.out/MobileAppsRendering-PROD.template.json
            mobile-apps-rendering-preview-cfn:
              - apps-rendering/cdk.out/MobileAppsRenderingPreview-CODE.template.json
              - apps-rendering/cdk.out/MobileAppsRenderingPreview-PROD.template.json
            mobile-apps-rendering:
              - apps-rendering/dist/server/mobile-apps-rendering.zip
            mobile-assets:
              - apps-rendering/dist/assets/
