name: Continuous Benchmarking
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'
  # We need to run on "pull_request" to get the PR number in the event.
  # When running on "push", we cannot add a comment to a specific PR.
  pull_request:
    #  If/when we compare results to `main`, we should also run on 'reopened'
    types: [opened, synchronize]
    # paths:
    #   - 'dotcom-rendering/**'
jobs:
  continuous_benchmarking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # TODO Re-enable this for demo!

      # - name: Install Node
      #   uses: guardian/actions-setup-node@main

      # # Cache npm dependencies using https://github.com/bahmutov/npm-install
      # - uses: bahmutov/npm-install@v1

      # - name: Generate production build
      #   run: make build
      #   working-directory: dotcom-rendering

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.21.0

      - name: Aggregate
        run: deno run --no-check --allow-net=api.github.com --allow-env="GITHUB_TOKEN","GITHUB_EVENT_PATH" --allow-read scripts/cb/main.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Comment a pull_request
      #   uses: mb2dev/github-action-comment-pull-request@1.0.0
      #   with:
      #     message: "Hello, It's my first comment with Github action !"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     reactions: '+1 | -1 | laugh | hooray | confused | heart | rocket | eyes'

  # create_comment:
  #   uses: peter-evans/create-or-update-comment@v2
  #   with:
  #     issue-number: ${{ github.event.pull_request.number }}
  #     body: |
  #       This is a multi-line test comment
  #       - With GitHub **Markdown** :sparkles:
  #       - Created by [create-or-update-comment][1]
  #       [1]: https://github.com/peter-evans/create-or-update-comment
  #     reactions: '+1'
# name: Continuous Benchmarking
# on:
#   push:
#     paths-ignore:
#       - 'apps-rendering/**'
#       - 'dotcom-rendering/docs/**'

# jobs:
#   name: Create comment
#     uses: peter-evans/create-or-update-comment@v2
#     with:
#       issue-number: ${{ github.event.pull_request.number }}
#       body: |
#         This is a multi-line test comment
#         - With GitHub **Markdown** :sparkles:
#         - Created by [create-or-update-comment][1]
#         [1]: https://github.com/peter-evans/create-or-update-comment
#       reactions: '+1'

# continuous_ben:
#   name: Typescript
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - uses: guardian/actions-setup-node@main

#     # Cache npm dependencies using https://github.com/bahmutov/npm-install
#     - uses: bahmutov/npm-install@v1

#     - name: Check typescript
#       run: yarn tsc
#       working-directory: dotcom-rendering

# - name: Create comment
#   uses: peter-evans/create-or-update-comment@v2
#   with:
#     issue-number: 1
#     body: |
#       This is a multi-line test comment
#       - With GitHub **Markdown** :sparkles:
#       - Created by [create-or-update-comment][1]

#       [1]: https://github.com/peter-evans/create-or-update-comment
#     reactions: '+1'
