name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
# name: Continuous Benchmarking
# on:
#   push:
#     paths-ignore:
#       - 'apps-rendering/**'
#       - 'dotcom-rendering/docs/**'

# jobs:
#   name: Create comment
#     uses: peter-evans/create-or-update-comment@v2
#     with:
#       issue-number: ${{ github.event.pull_request.number }}
#       body: |
#         This is a multi-line test comment
#         - With GitHub **Markdown** :sparkles:
#         - Created by [create-or-update-comment][1]
#         [1]: https://github.com/peter-evans/create-or-update-comment
#       reactions: '+1'

# continuous_ben:
#   name: Typescript
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - uses: guardian/actions-setup-node@main

#     # Cache npm dependencies using https://github.com/bahmutov/npm-install
#     - uses: bahmutov/npm-install@v1

#     - name: Check typescript
#       run: yarn tsc
#       working-directory: dotcom-rendering

# - name: Create comment
#   uses: peter-evans/create-or-update-comment@v2
#   with:
#     issue-number: 1
#     body: |
#       This is a multi-line test comment
#       - With GitHub **Markdown** :sparkles:
#       - Created by [create-or-update-comment][1]

#       [1]: https://github.com/peter-evans/create-or-update-comment
#     reactions: '+1'
