on:
  workflow_call:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - name: Run Jest
        run: CI=true pnpm test
        working-directory: dotcom-rendering
